--liquibase formatted sql
--changeset anton_torba:create-categories-table
CREATE TABLE CATEGORIES
(
    ID BIGINT IDENTITY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRODUCT_COUNT INT NOT NULL,
    CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID)
);

--changeset anton_torba:create-products-table
CREATE TABLE PRODUCTS
(
    ID BIGINT IDENTITY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID)
);

--changeset anton_torba:create-products_categories-table
CREATE TABLE PRODUCTS_CATEGORIES
(
    PRODUCT_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL
);

--changeset anton_torba:indexing_categories
CREATE INDEX CATEGORY_ID_KEY_INDEX_6 ON PRODUCTS_CATEGORIES(CATEGORY_ID);

--changeset anton_torba:indexing_products
CREATE INDEX PRODUCT_ID_KEY_INDEX_6 ON PRODUCTS_CATEGORIES(PRODUCT_ID);

--changeset anton_torba:add_category_constraint
ALTER TABLE PRODUCTS_CATEGORIES
ADD CONSTRAINT CATEGORY_ID_KEY
FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORIES (ID)
ON UPDATE CASCADE ON DELETE CASCADE;

--changeset anton_torba:add_product_constraint
ALTER TABLE PRODUCTS_CATEGORIES
ADD CONSTRAINT PRODUCT_ID_KEY
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCTS (ID)
ON UPDATE CASCADE ON DELETE CASCADE;


