on: workflow_dispatch
name: Docker Image Azure Container Instance Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        ## to delete
      - name: Verify run id
        run: echo Run Id $GITHUB_RUN_ID
      - name: Output the branch name
        run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
        # && github.ref == 'refs/heads/master' not necessary
        ## commented block

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          mvn -B package --file pom.xml
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-app
          location: 'west europe'
